/**
 * update-summary.mjs
 * Generates ../docs/project-summary.html with the current project state.
 * Run via:  npm run summary   (alias: npm run s)
 */

import { execSync } from "child_process";
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../docs/project-summary.html");

// ── Git changelog (last 30 commits) ──────────────────────────────────────────
let changelogHtml = "";
try {
  const log = execSync('git log --pretty=format:"%ad|%s" --date=format:"%d.%m.%Y" -30', {
    cwd: join(__dirname, ".."),
  }).toString().trim();

  const entries = {};
  for (const line of log.split("\n")) {
    const [date, ...rest] = line.split("|");
    const msg = rest.join("|").trim();
    if (!entries[date]) entries[date] = [];
    entries[date].push(msg);
  }

  changelogHtml = Object.entries(entries).map(([date, msgs]) => `
    <div class="entry">
      <div class="date">${date}</div>
      ${msgs.map(m => `<p>${m}</p>`).join("")}
    </div>`).join("");
} catch {
  changelogHtml = `<div class="entry"><div class="date">–</div><p>Git log not available.</p></div>`;
}

// ── Date ──────────────────────────────────────────────────────────────────────
const today = new Date().toLocaleDateString("de-DE", {
  day: "2-digit", month: "2-digit", year: "numeric",
});

// ── HTML ─────────────────────────────────────────────────────────────────────
const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Project Summary – CPQ-NA-Webtester</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<style>
  body { font-family: system-ui, sans-serif; max-width: 1200px; margin: 40px auto; padding: 0 24px; color: #1a1a1a; background: #f9f9f9; }
  h1 { font-size: 2rem; border-bottom: 3px solid #e05a00; padding-bottom: 10px; }
  h2 { font-size: 1.3rem; margin-top: 2.5rem; color: #e05a00; }
  h3 { font-size: 1rem; color: #444; margin-top: 1.2rem; margin-bottom: 4px; }
  .meta { color: #666; font-size: 0.9rem; margin-bottom: 2rem; }
  .card { background: white; border-radius: 10px; padding: 20px 28px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.07); }
  .badge { display: inline-block; color: white; border-radius: 20px; padding: 3px 12px; font-size: 0.8rem; margin: 2px; background: #e05a00; }
  .badge.green { background: #2e7d32; }
  .badge.blue { background: #1565c0; }
  .badge.grey { background: #666; }
  .badge.purple { background: #6a1b9a; }
  .badge.teal { background: #00695c; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  th { background: #f0f0f0; text-align: left; padding: 8px 12px; font-size: 0.85rem; color: #444; }
  td { padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 0.9rem; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .status { font-weight: bold; }
  .ok { color: #2e7d32; }
  .wip { color: #e65100; }
  .open { color: #999; }
  .mermaid { background: #fafafa; border-radius: 8px; padding: 20px; margin-top: 10px; overflow-x: auto; }
  ul { line-height: 1.9; padding-left: 20px; }
  ol { line-height: 1.9; padding-left: 20px; }
  .changelog { border-left: 3px solid #e05a00; padding-left: 16px; margin-top: 10px; }
  .changelog .entry { margin-bottom: 16px; }
  .changelog .date { font-weight: bold; font-size: 0.85rem; color: #e05a00; }
  .changelog p { margin: 4px 0; font-size: 0.9rem; color: #444; }
  .two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
  .three-col { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; }
  @media (max-width: 900px) { .two-col, .three-col { grid-template-columns: 1fr; } }
  code { background: #f0f0f0; padding: 1px 5px; border-radius: 3px; font-size: 0.85em; font-family: monospace; }
  .step-num { display: inline-block; background: #e05a00; color: white; border-radius: 50%; width: 20px; height: 20px; text-align: center; line-height: 20px; font-size: 0.75rem; font-weight: bold; margin-right: 6px; flex-shrink: 0; }
  .step-row { display: flex; align-items: flex-start; margin-bottom: 6px; }
  .step-row span { line-height: 1.5; font-size: 0.9rem; }
  .vin-dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 6px; }
  .note { background: #fff8e1; border-left: 3px solid #f9a825; padding: 10px 14px; border-radius: 4px; margin-top: 10px; font-size: 0.88rem; }
</style>
</head>
<body>

<h1>📋 Project Summary: CPQ-NA-Webtester</h1>
<div class="meta">Last updated: ${today} · Generated by <code>npm run summary</code> · Repository: <code>Robert-Engstler/cpq-na-webtester</code></div>

<!-- ── Project Goal ── -->
<div class="card">
  <h2>🎯 Project Goal</h2>
  <p>An internal web app (hosted on Vercel) that lets AGCO staff run automated end-to-end Playwright tests against the North America CPQ (Configure, Price, Quote) website. Tests cover the full <strong>Genuine Care</strong> flow per VIN:</p>
  <ul>
    <li>Login with CPQ credentials</li>
    <li>Machine search and selection by VIN</li>
    <li>Genuine Care type selection (Annual / Standard / Parts-Only)</li>
    <li>Service Condition selection per GC type</li>
    <li>Specification configuration (pre-populated by sales codes, or manual selection)</li>
    <li>Save configuration and capture Configuration ID</li>
    <li>PDF download (PartsPicklist + ServiceChecklist)</li>
    <li>For Stage + Order endpoint: quote creation and order placement with Order ID capture</li>
  </ul>
  <p>Results are reported back in real time via incremental webhook updates. Up to 10 VINs can be tested per scenario run.</p>
</div>

<!-- ── Tech Stack ── -->
<div class="card">
  <h2>🛠 Tech Stack</h2>
  <p>
    <span class="badge blue">Next.js 16 (App Router)</span>
    <span class="badge blue">TypeScript</span>
    <span class="badge blue">React 19</span>
    <span class="badge blue">Tailwind CSS 4</span>
    <span class="badge green">Vercel (hosting)</span>
    <span class="badge green">Neon PostgreSQL</span>
    <span class="badge green">Vercel Blob (file storage)</span>
    <span class="badge purple">GitHub Actions</span>
    <span class="badge purple">Playwright 1.58</span>
    <span class="badge grey">HMAC-SHA256 Auth (jose)</span>
    <span class="badge teal">@vercel/postgres</span>
  </p>
  <table style="margin-top:16px;">
    <tr><th>Layer</th><th>Technology</th><th>Purpose</th></tr>
    <tr><td>Frontend &amp; Backend</td><td>Next.js 16, App Router, TypeScript</td><td>UI and API routes, hosted on Vercel</td></tr>
    <tr><td>Styling</td><td>Tailwind CSS 4, JetBrains Mono</td><td>Dark monospace theme, design tokens in <code>src/lib/design.ts</code></td></tr>
    <tr><td>Database</td><td>Neon PostgreSQL via <code>@vercel/postgres</code></td><td>Scenarios, test runs, results, settings</td></tr>
    <tr><td>File Storage</td><td>Vercel Blob</td><td>Failure screenshots and zipped PDFs per run</td></tr>
    <tr><td>Test Execution</td><td>GitHub Actions (ubuntu-latest, 20 min timeout)</td><td>Runs Playwright in a Linux environment</td></tr>
    <tr><td>Browser Automation</td><td>Playwright + Chromium</td><td>End-to-end UI test of CPQ NA website</td></tr>
    <tr><td>Auth</td><td>HMAC-SHA256 cookie via <code>jose</code></td><td>Single-password access; admin password for settings</td></tr>
    <tr><td>Source Control / CI</td><td>GitHub (private repo)</td><td>Auto-deploy to Vercel on push to <code>main</code></td></tr>
  </table>
</div>

<!-- ── System Flow ── -->
<div class="card">
  <h2>🏗 System Flow</h2>
  <div class="mermaid">
flowchart TD
    A([👤 User]) --> B[Login with CPQ credentials\nEnvironment · Brand · Country]
    B --> C[Create Scenario\nVINs + GC types + Service Conditions]
    C --> D[Click Run]
    D --> E[POST /api/runs/trigger\nCreates pending run record in DB\nResets created_at for accurate timer]
    E --> F[GitHub Actions workflow_dispatch\nPasses all inputs + secrets]
    F --> G[Playwright script starts\ncpq-na-test.mjs on ubuntu-latest]
    G --> H[Per-VIN loop\nSee Playwright Steps below]
    H --> I[POST /api/runs/webhook type:step\nIncremental result update per step]
    I --> J[Run Details page\nLive polling every 5s]
    H --> K{Stage + Order?}
    K -->|Yes| L[Create Quote → Place Order\nCapture Order ID]
    K -->|No| M[Config test only\norder_id = config test only]
    L --> N[Final webhook POST\nstatus + order_ids + pdf_url + finished_at]
    M --> N
  </div>
</div>

<!-- ── Pages ── -->
<div class="card">
  <h2>📄 Pages</h2>

  <h3>Login (<code>/login</code>)</h3>
  <ul>
    <li>CPQ username + password fields (pre-filled from Login Defaults if configured)</li>
    <li>Environment selector: <strong>Prod</strong> / <strong>Stage</strong></li>
    <li>Brand selector: <strong>FT</strong> (Fendt) / <strong>MF</strong> (Massey Ferguson)</li>
    <li>Country selector: <strong>US</strong> / <strong>CA</strong></li>
    <li>Credentials stored in HMAC-signed session cookie (7-day expiry, HTTPOnly)</li>
    <li>Login Defaults: per env/brand/country credential pre-fill (configured in Settings)</li>
  </ul>

  <h3>Scenarios (<code>/scenarios</code>) — default landing page</h3>
  <ul>
    <li>Add Scenario form: Description field, per-row VIN inputs (up to 10), GC type buttons per VIN, optional Service Condition column</li>
    <li>Excel paste support: paste multi-line VINs from clipboard, distributed across rows</li>
    <li>GC types: <strong>Annual</strong> / <strong>Standard</strong> / <strong>Parts-Only</strong> — button group per VIN row</li>
    <li>Service Condition: dropdown per VIN — duration (12/24/36/48/60 mo) for Annual; Minimum/Medium/Maximum for Standard/Parts-Only</li>
    <li>Service Condition column hidden by default — toggled in Settings (<code>show_svc_column</code>)</li>
    <li>Scenario list: paginated table (5/page), columns: ID · Description · VINs/GC · Created · Run/Delete buttons</li>
    <li>Clicking Run triggers workflow and navigates to /runs</li>
    <li>Auto-delete: scenarios older than 30 days deleted on every GET /api/scenarios</li>
  </ul>

  <h3>Runs (<code>/runs</code>)</h3>
  <ul>
    <li>Paginated run history (5/page, newest first), auto-refresh every 5 s while any run is pending</li>
    <li>Columns: Run ID · Scenario · VINs (color-coded) · Config IDs (clickable links) · Environment/Brand/Country · Status · Duration · PDF · Details</li>
    <li>Status badges: animated RUNNING (left-to-right sweep) · COMPLETED · FAILED · STOPPED</li>
    <li>Live ticking duration counter while run is active; freezes on completion</li>
    <li>VIN color coding: 🟢 green (all specs pre-populated) · 🟡 yellow (manual spec selection needed) · 🔴 red (step failed) · ⚫ gray (pending)</li>
    <li>PDF download button links to zipped PDFs on Vercel Blob</li>
    <li>Run ID format: <code>R-xxxxxx</code> (first 6 chars of UUID)</li>
  </ul>

  <h3>Run Details (<code>/runs/[id]</code>) — opens in new tab</h3>
  <ul>
    <li>No nav bar (standalone page context)</li>
    <li>Header: Run ID · Scenario ID · VINs · Status · Started · Duration · PDF download</li>
    <li>Step-by-step table: Step name · Result (✓/✗) · Duration (ms) · URL · Screenshot (on failure)</li>
    <li>Steps prefixed with <code>[VIN_LABEL]</code> for easy identification</li>
    <li>Config IDs shown as clickable CPQ configuration links</li>
    <li>"Copy for Claude" share button — copies public read-only URL to clipboard for AI analysis</li>
    <li>Raw JSON toggle for full result inspection</li>
    <li>Live polling every 5 s while run is pending; stops on completion</li>
  </ul>

  <h3>Settings Modal (nav bar → Settings)</h3>
  <ul>
    <li>Admin password required for all changes</li>
    <li><strong>Scenario Defaults tab:</strong> GC default · Annual duration · SVC preset · Stage endpoint · SVC column visibility</li>
    <li><strong>Login Defaults tab:</strong> per env/brand/country credential pre-fill (up to 8 combos)</li>
    <li>Service Condition preset descriptions: Minimum (start: 2nd lowest, last: 2nd lowest, 12 mo) · Medium (start: 2nd lowest, last: 6th lowest, 48 mo) · Maximum (start: Lowest, last: Highest, highest available)</li>
  </ul>

  <h3>Mock page (<code>/mock</code>)</h3>
  <ul>
    <li>Static design reference with hardcoded data demonstrating all UI states</li>
  </ul>
</div>

<!-- ── Playwright Test Flow ── -->
<div class="card">
  <h2>🎭 Playwright Test Flow (<code>tests/cpq-na-test.mjs</code>)</h2>
  <p>Runs as a Node.js script in GitHub Actions. One Chromium browser, fresh tab per VIN. Steps are reported to the webhook incrementally as <code>type:step</code> payloads.</p>

  <h3>Phase A — Login (once per run)</h3>
  <div class="step-row"><span class="step-num">1</span><span>Navigate to CPQ URL</span></div>
  <div class="step-row"><span class="step-num">2</span><span>Enter username + password (resolved from <code>CPQ_PASSWORDS</code> JSON secret by Env|Brand|Country key — never passed as plain input to avoid log exposure)</span></div>
  <div class="step-row"><span class="step-num">3</span><span>Submit login form, wait for dashboard</span></div>

  <h3>Phase B — Per-VIN loop</h3>
  <div class="step-row"><span class="step-num">1</span><span><strong>Search machine by VIN</strong> — enter VIN in search field, select result</span></div>
  <div class="step-row"><span class="step-num">2</span><span><strong>Select Genuine Care type</strong> — Annual / Standard / Parts-Only (per-VIN from <code>GC_OPTIONS</code>)</span></div>
  <div class="step-row"><span class="step-num">3</span><span><strong>Select Service Condition</strong> — duration (Annual) or preset (Standard/Parts-Only) from <code>SVC_OPTIONS</code></span></div>
  <div class="step-row"><span class="step-num">4</span><span><strong>Configure specifications</strong> — pre-populated options accepted as-is; un-populated options selected manually (tracked as <code>hadManualSpec: true</code>)</span></div>
  <div class="step-row"><span class="step-num">5</span><span><strong>Save configuration</strong> — clicks Save Config, captures <code>CONFIGxxxxxxxx</code> configuration ID</span></div>
  <div class="step-row"><span class="step-num">6</span><span><strong>Download PDFs</strong> — PartsPicklist + ServiceChecklist per VIN, zipped and uploaded to Vercel Blob</span></div>

  <h3>Phase C — Stage + Order (conditional)</h3>
  <div class="step-row"><span class="step-num">7</span><span><strong>Create quote</strong> — only if <code>ENVIRONMENT=Stage</code> AND <code>STAGE_ENDPOINT=Order</code></span></div>
  <div class="step-row"><span class="step-num">8</span><span><strong>Place order</strong> — captures order ID, stored in <code>order_ids</code> map (VIN → order ID)</span></div>

  <h3>Failure handling</h3>
  <ul>
    <li>On any step failure: screenshot captured, uploaded to Vercel Blob, URL included in step result</li>
    <li>Step result includes: <code>step</code>, <code>passed</code>, <code>url</code>, <code>durationMs</code>, <code>error</code>, <code>screenshotUrl</code>, optional <code>configId</code>/<code>configUrl</code>, <code>hadManualSpec</code>, <code>manualSpecs[]</code></li>
    <li>Each step POSTs to webhook immediately (<code>type:step</code>) so the UI updates in real time</li>
    <li>Final POST includes: <code>type:result</code>, <code>status</code>, full <code>results[]</code>, <code>order_ids</code>, <code>pdf_url</code></li>
    <li>Run can be stopped via <code>POST /api/runs/[id]/stop</code> — sets status to <code>stopped</code></li>
  </ul>

  <h3>Local development mode</h3>
  <p class="note">When run locally (without <code>WEBHOOK_URL</code>/<code>WEBHOOK_SECRET</code>/<code>RUN_ID</code>), the script runs in local mode: test executes normally but results are not posted to the webhook. <code>.env.local</code> is loaded automatically from the repo root.</p>
</div>

<!-- ── GitHub Actions Workflow ── -->
<div class="card">
  <h2>⚙️ GitHub Actions Workflow (<code>.github/workflows/test.yml</code>)</h2>
  <p>Name: <strong>CPQ NA Test Run</strong> · Trigger: <code>workflow_dispatch</code> only · Runner: <code>ubuntu-latest</code> · Timeout: 20 minutes</p>

  <h3>Workflow inputs (passed from /api/runs/trigger)</h3>
  <table>
    <tr><th>Input</th><th>Required</th><th>Default</th><th>Description</th></tr>
    <tr><td><code>vins</code></td><td>Yes</td><td>—</td><td>Comma-separated VINs</td></tr>
    <tr><td><code>gc_options</code></td><td>Yes</td><td>—</td><td>Comma-separated GC types (Annual|Standard|Parts-Only), parallel to vins</td></tr>
    <tr><td><code>run_id</code></td><td>Yes</td><td>—</td><td>UUID of the test_run DB record</td></tr>
    <tr><td><code>environment</code></td><td>Yes</td><td>—</td><td>Prod | Stage</td></tr>
    <tr><td><code>brand</code></td><td>Yes</td><td>—</td><td>FT | MF</td></tr>
    <tr><td><code>country</code></td><td>Yes</td><td>—</td><td>US | CA</td></tr>
    <tr><td><code>cpq_username</code></td><td>Yes</td><td>—</td><td>CPQ login username</td></tr>
    <tr><td><code>cpq_url</code></td><td>Yes</td><td>—</td><td>Resolved CPQ base URL</td></tr>
    <tr><td><code>stage_endpoint</code></td><td>No</td><td>Configuration</td><td>Where Stage test ends: Configuration | Order</td></tr>
    <tr><td><code>gc_default</code></td><td>No</td><td>Standard</td><td>Default GC type fallback</td></tr>
    <tr><td><code>annual_duration</code></td><td>No</td><td>60</td><td>Annual duration in months</td></tr>
    <tr><td><code>svc_preset</code></td><td>No</td><td>Minimum</td><td>Service condition preset</td></tr>
    <tr><td><code>svc_options</code></td><td>No</td><td>""</td><td>Per-VIN service condition overrides, parallel to vins</td></tr>
  </table>

  <h3>GitHub Actions secrets (configured in repo settings)</h3>
  <table>
    <tr><th>Secret</th><th>Description</th></tr>
    <tr><td><code>CPQ_PASSWORDS</code></td><td>JSON map: <code>"Env|Brand|Country" → password</code> (never exposed in logs)</td></tr>
    <tr><td><code>WEBHOOK_URL</code></td><td>Full URL to Vercel webhook endpoint</td></tr>
    <tr><td><code>WEBHOOK_SECRET</code></td><td>HMAC bearer token for webhook validation</td></tr>
    <tr><td><code>BLOB_READ_WRITE_TOKEN</code></td><td>Vercel Blob access token for screenshot/PDF upload</td></tr>
  </table>
</div>

<!-- ── API Routes ── -->
<div class="card">
  <h2>🔌 API Routes</h2>
  <table>
    <tr><th>Method</th><th>Route</th><th>Auth</th><th>Description</th></tr>
    <tr><td>POST</td><td><code>/api/auth/login</code></td><td>Public</td><td>Body: <code>{ password, environment, brand, country, cpq_username, cpq_password }</code> — validates password, sets HMAC-signed session cookie</td></tr>
    <tr><td>POST</td><td><code>/api/auth/logout</code></td><td>Session</td><td>Clears <code>auth_session</code> cookie</td></tr>
    <tr><td>POST</td><td><code>/api/db/migrate</code></td><td>Session</td><td>Creates/updates DB tables from schema</td></tr>
    <tr><td>GET</td><td><code>/api/scenarios</code></td><td>Session</td><td>List all scenarios (newest first); triggers 30-day auto-delete</td></tr>
    <tr><td>POST</td><td><code>/api/scenarios</code></td><td>Session</td><td>Create scenario — body: <code>{ name, vins[], gc_options[], svc_options[] }</code></td></tr>
    <tr><td>DELETE</td><td><code>/api/scenarios/[id]</code></td><td>Session</td><td>Delete scenario + cascade delete test_runs</td></tr>
    <tr><td>GET</td><td><code>/api/runs</code></td><td>Session</td><td>List runs (optional <code>?scenario_id=</code> filter); triggers 30-day auto-delete</td></tr>
    <tr><td>DELETE</td><td><code>/api/runs</code></td><td>Session</td><td>Delete all runs (optional <code>?scenario_id=</code> filter)</td></tr>
    <tr><td>GET</td><td><code>/api/runs/[id]</code></td><td>Session</td><td>Get single run with full result_json</td></tr>
    <tr><td>DELETE</td><td><code>/api/runs/[id]</code></td><td>Session</td><td>Delete single run</td></tr>
    <tr><td>POST</td><td><code>/api/runs/[id]/stop</code></td><td>Session</td><td>Set run status to <code>stopped</code>, set <code>finished_at</code></td></tr>
    <tr><td>POST</td><td><code>/api/runs/trigger</code></td><td>Session</td><td>Create pending run, dispatch GitHub Actions <code>workflow_dispatch</code> with all inputs</td></tr>
    <tr><td>POST</td><td><code>/api/runs/webhook</code></td><td>Public (HMAC)</td><td>Receives step/result POSTs from GitHub Actions; HMAC-Bearer validated; updates run record incrementally</td></tr>
    <tr><td>GET</td><td><code>/api/share/[id]</code></td><td>Public</td><td>Read-only run data for public share links (UUID unguessability as access control)</td></tr>
    <tr><td>GET</td><td><code>/api/settings/app</code></td><td>Session</td><td>Get app settings (singleton row)</td></tr>
    <tr><td>PUT</td><td><code>/api/settings/app</code></td><td>Admin pwd</td><td>Update app settings — body: <code>{ gc_default, annual_duration, svc_preset, stage_endpoint, show_svc_column }</code></td></tr>
    <tr><td>GET</td><td><code>/api/settings/login-defaults</code></td><td>Session</td><td>List all login default rows (up to 8)</td></tr>
    <tr><td>POST</td><td><code>/api/settings/login-defaults</code></td><td>Admin pwd</td><td>Upsert login default — body: <code>{ environment, brand, country, cpq_username, cpq_password }</code></td></tr>
    <tr><td>POST</td><td><code>/api/settings/verify</code></td><td>Session</td><td>Verify admin password — returns <code>{ ok: true/false }</code></td></tr>
  </table>
</div>

<!-- ── Database Schema ── -->
<div class="card">
  <h2>🗄 Database Schema</h2>

  <h3><code>app_settings</code> (singleton — always exactly 1 row)</h3>
  <table>
    <tr><th>Column</th><th>Type</th><th>Description</th></tr>
    <tr><td><code>id</code></td><td>INTEGER</td><td>Always 1</td></tr>
    <tr><td><code>gc_default</code></td><td>TEXT</td><td>Annual | Standard | Parts-Only</td></tr>
    <tr><td><code>annual_duration</code></td><td>INTEGER</td><td>12 | 24 | 36 | 48 | 60 months</td></tr>
    <tr><td><code>svc_preset</code></td><td>TEXT</td><td>Minimum | Medium | Maximum</td></tr>
    <tr><td><code>stage_endpoint</code></td><td>TEXT</td><td>Configuration | Order (where Stage test stops)</td></tr>
    <tr><td><code>show_svc_column</code></td><td>BOOLEAN</td><td>Whether the Service Condition column is visible in the Scenarios form</td></tr>
  </table>

  <h3><code>login_defaults</code> (up to 8 rows — one per env/brand/country combo)</h3>
  <table>
    <tr><th>Column</th><th>Type</th><th>Description</th></tr>
    <tr><td><code>environment</code></td><td>TEXT</td><td>Prod | Stage</td></tr>
    <tr><td><code>brand</code></td><td>TEXT</td><td>FT | MF</td></tr>
    <tr><td><code>country</code></td><td>TEXT</td><td>US | CA</td></tr>
    <tr><td><code>cpq_username</code></td><td>TEXT</td><td>Pre-filled login username</td></tr>
    <tr><td><code>cpq_password</code></td><td>TEXT</td><td>Pre-filled login password</td></tr>
  </table>

  <h3><code>scenarios</code></h3>
  <table>
    <tr><th>Column</th><th>Type</th><th>Description</th></tr>
    <tr><td><code>id</code></td><td>UUID</td><td>Primary key</td></tr>
    <tr><td><code>name</code></td><td>TEXT</td><td>User-defined scenario description</td></tr>
    <tr><td><code>vins</code></td><td>TEXT[]</td><td>Vehicle Identification Numbers (1–10)</td></tr>
    <tr><td><code>gc_options</code></td><td>TEXT[]</td><td>Annual | Standard | Parts-Only — one per VIN, parallel to <code>vins</code></td></tr>
    <tr><td><code>svc_options</code></td><td>TEXT[]</td><td>Service condition overrides — duration string for Annual, preset for Standard/Parts-Only</td></tr>
    <tr><td><code>created_at</code></td><td>TIMESTAMP</td><td>Creation date (auto-deleted after 30 days)</td></tr>
  </table>

  <h3><code>test_runs</code></h3>
  <table>
    <tr><th>Column</th><th>Type</th><th>Description</th></tr>
    <tr><td><code>id</code></td><td>UUID</td><td>Primary key</td></tr>
    <tr><td><code>scenario_id</code></td><td>UUID</td><td>FK → scenarios (cascade delete)</td></tr>
    <tr><td><code>environment</code></td><td>TEXT</td><td>Prod | Stage</td></tr>
    <tr><td><code>brand</code></td><td>TEXT</td><td>FT | MF</td></tr>
    <tr><td><code>country</code></td><td>TEXT</td><td>US | CA</td></tr>
    <tr><td><code>status</code></td><td>TEXT</td><td>pending | complete | failed | stopped</td></tr>
    <tr><td><code>result_json</code></td><td>JSONB</td><td>Step-by-step pass/fail results array — updated incrementally by webhook</td></tr>
    <tr><td><code>screenshot_url</code></td><td>TEXT</td><td>Vercel Blob URL (failure screenshot)</td></tr>
    <tr><td><code>pdf_url</code></td><td>TEXT</td><td>Vercel Blob URL (zipped PDFs for all VINs in run)</td></tr>
    <tr><td><code>pdf_text</code></td><td>TEXT</td><td>Extracted PDF text (future — Phase 3)</td></tr>
    <tr><td><code>performance_json</code></td><td>JSONB</td><td>Core Web Vitals (future — Phase 5)</td></tr>
    <tr><td><code>order_ids</code></td><td>JSONB</td><td>Map: VIN → order ID (Stage/Order) or "config test only" (Prod/Config)</td></tr>
    <tr><td><code>created_at</code></td><td>TIMESTAMP</td><td>Run start time — reset when GitHub dispatch succeeds for accurate timer</td></tr>
    <tr><td><code>finished_at</code></td><td>TIMESTAMP</td><td>Run end time (set by final webhook POST)</td></tr>
  </table>

  <p class="note"><strong>Auto-delete:</strong> runs and scenarios older than 30 days are deleted on every <code>GET /api/scenarios</code> and <code>GET /api/runs</code> request.</p>
</div>

<!-- ── Auth & Middleware ── -->
<div class="card">
  <h2>🔐 Auth &amp; Middleware</h2>
  <ul>
    <li>Middleware: <code>src/proxy.ts</code> — checks <code>auth_session</code> cookie on all routes except public paths</li>
    <li>Public paths: <code>/login</code>, <code>/api/auth/*</code>, <code>/api/runs/webhook</code>, <code>/api/share/*</code></li>
    <li>Session cookie: HMAC-SHA256 signed (via <code>jose</code>), HTTPOnly, SameSite=Lax, 7-day expiry</li>
    <li>Cookie payload includes: <code>environment</code>, <code>brand</code>, <code>country</code>, <code>cpq_username</code>, <code>cpq_password</code></li>
    <li><strong>APP_PASSWORD</strong>: general access (login page)</li>
    <li><strong>ADMIN_PASSWORD</strong>: settings changes (verified via <code>/api/settings/verify</code> on modal open)</li>
    <li>Webhook auth: HMAC-Bearer token validation (secret shared between Vercel and GitHub Actions)</li>
    <li>CPQ passwords: stored as JSON map in GitHub secret <code>CPQ_PASSWORDS</code> — never passed as plain workflow input</li>
  </ul>
</div>

<!-- ── Environment Variables ── -->
<div class="card">
  <h2>🔑 Environment Variables</h2>
  <h3>Vercel / <code>.env.local</code></h3>
  <table>
    <tr><th>Variable</th><th>Description</th></tr>
    <tr><td><code>APP_PASSWORD</code></td><td>General app login password</td></tr>
    <tr><td><code>ADMIN_PASSWORD</code></td><td>Admin password for settings changes</td></tr>
    <tr><td><code>AUTH_SECRET</code></td><td>HMAC key for session cookie signing</td></tr>
    <tr><td><code>DATABASE_URL</code></td><td>Neon PostgreSQL connection string</td></tr>
    <tr><td><code>BLOB_READ_WRITE_TOKEN</code></td><td>Vercel Blob access token (screenshots + PDFs)</td></tr>
    <tr><td><code>GITHUB_TOKEN</code></td><td>GitHub PAT for triggering workflow_dispatch</td></tr>
    <tr><td><code>GITHUB_REPO</code></td><td><code>Robert-Engstler/cpq-na-webtester</code></td></tr>
    <tr><td><code>WEBHOOK_SECRET</code></td><td>HMAC secret for validating GitHub Actions POSTs</td></tr>
  </table>
  <h3>GitHub Actions secrets</h3>
  <table>
    <tr><th>Secret</th><th>Description</th></tr>
    <tr><td><code>CPQ_PASSWORDS</code></td><td>JSON map <code>"Env|Brand|Country" → password</code></td></tr>
    <tr><td><code>WEBHOOK_URL</code></td><td>Full Vercel webhook URL</td></tr>
    <tr><td><code>WEBHOOK_SECRET</code></td><td>Matches Vercel <code>WEBHOOK_SECRET</code></td></tr>
    <tr><td><code>BLOB_READ_WRITE_TOKEN</code></td><td>Matches Vercel <code>BLOB_READ_WRITE_TOKEN</code></td></tr>
  </table>
</div>

<!-- ── Component Status ── -->
<div class="card">
  <h2>📊 Component Status</h2>
  <table>
    <tr><th>Component</th><th>Description</th><th>Status</th></tr>
    <tr><td><strong>Login page</strong></td><td>CPQ credential login, env/brand/country selection, Login Defaults modal (per-combo pre-fill)</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Scenarios page</strong></td><td>Per-VIN rows, GC type buttons, Service Condition column (optional toggle), Excel paste, description field, up to 10 VINs</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Scenario Defaults (Settings)</strong></td><td>GC default, annual duration, SVC preset, stage endpoint, SVC column visibility — all button groups</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Runs page</strong></td><td>Live polling, animated RUNNING badge, per-VIN status/color/order IDs, duration counter, PDF download</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Run Details page</strong></td><td>Per-step table with duration, URL, screenshot; "Copy for Claude" share button; raw JSON toggle</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Trigger API</strong></td><td>Creates pending run, dispatches GitHub Actions with all inputs including svc_options; resets created_at on dispatch success</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Webhook API</strong></td><td>HMAC-verified, incremental step updates (type:step) + final result POST, sets finished_at</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Stop Run API</strong></td><td>POST /api/runs/[id]/stop — sets status to stopped, sets finished_at</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Share API</strong></td><td>Public read-only run endpoint (<code>/api/share/[id]</code>) — UUID unguessability as access control</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Settings Modal</strong></td><td>App settings + Login Defaults tabs, admin password verification</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Playwright script</strong></td><td>Full NA CPQ flow — all 9 Brand/Country/GC combos confirmed passing for both Configuration and Order endpoints (Stage, single VIN)</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>DB schema + migration</strong></td><td>All tables including svc_options and show_svc_column columns</td><td class="status ok">✅ Done</td></tr>
    <tr><td><strong>Vercel deployment</strong></td><td>Auto-deploys on push to main via GitHub integration</td><td class="status ok">✅ Done</td></tr>
  </table>
</div>

<!-- ── Two-col: To Do + Key Decisions ── -->
<div class="two-col">
  <div class="card">
    <h2>⬜ Still To Do</h2>
    <ul>
      <li>Confirm all GitHub Actions secrets are set in repo settings</li>
      <li>Validate PDF download + Blob upload from GitHub Actions runner</li>
      <li>Test Multi-VIN run (<code>VINS=VIN1,VIN2</code>) — VINs 2+ use <code>goto()</code> + <code>loginIfNeeded()</code></li>
      <li>Test Prod environment — journey ends at Save Config (no Quote/Order)</li>
    </ul>
  </div>
  <div class="card">
    <h2>🔑 Key Design Decisions</h2>
    <ul>
      <li>CPQ credentials passed directly from session cookie to GitHub Actions inputs — no separate app password</li>
      <li>CPQ password stored as JSON map in one GitHub secret (<code>CPQ_PASSWORDS</code>) — never exposed in workflow inputs/logs</li>
      <li>Session stored as HMAC-signed cookie via <code>jose</code> library</li>
      <li>Incremental webhook updates (<code>type:step</code>) for live UI — no polling of GitHub API</li>
      <li>Service Condition column hidden by default — toggled per deployment via Settings</li>
      <li>UUID unguessability used for public share links — no extra access token needed</li>
      <li><code>svc_options</code> stored as <code>TEXT[]</code> parallel to <code>vins[]</code></li>
      <li><code>created_at</code> reset on dispatch success so duration timer is accurate</li>
      <li>Run status simplified: only <code>pending</code>, <code>complete</code>, <code>failed</code>, <code>stopped</code> — no intermediate <code>running</code> state in DB</li>
    </ul>
  </div>
</div>

<!-- ── Future Phases ── -->
<div class="card">
  <h2>🔭 Future Phases (Parked)</h2>
  <table>
    <tr><th>Phase</th><th>Feature</th><th>Status</th><th>Notes</th></tr>
    <tr>
      <td>Phase 2</td>
      <td>Failure Screenshots</td>
      <td class="status wip">Infrastructure done</td>
      <td>Screenshot capture + Blob upload already implemented in Playwright script. Remaining: display screenshots inline below failed steps in Run Details UI.</td>
    </tr>
    <tr>
      <td>Phase 3</td>
      <td>PDF Text Extraction</td>
      <td class="status wip">PDF infra done</td>
      <td>PDF download + zip + Blob upload done. Remaining: extract text using <code>pdf-parse</code>, include in webhook payload, show collapsible section in Run Details.</td>
    </tr>
    <tr>
      <td>Phase 4</td>
      <td>Results UI Polish</td>
      <td class="status open">Parked</td>
      <td>Live log streaming (push-based), re-run button, run history per scenario, side-by-side comparison view, filter/sort controls, "Run All" button for parallel execution.</td>
    </tr>
    <tr>
      <td>Phase 5</td>
      <td>Performance Metrics</td>
      <td class="status open">Parked</td>
      <td>Core Web Vitals (LCP, FCP, CLS), custom interaction timings, trend charts, configurable pass/fail thresholds. Column <code>performance_json</code> already in schema.</td>
    </tr>
    <tr>
      <td>Phase 6</td>
      <td>Auto VIN Fetching from Redshift</td>
      <td class="status open">Parked</td>
      <td>Replace manual VIN entry with dropdown from data warehouse. Options: Redshift Data API / local Python bridge / scheduled export. SQL query configurable in Settings.</td>
    </tr>
  </table>
</div>

<!-- ── Changelog ── -->
<div class="card">
  <h2>📝 Changelog (from git — last 30 commits)</h2>
  <div class="changelog">
    ${changelogHtml}
  </div>
</div>

<script>mermaid.initialize({ startOnLoad: true, theme: 'neutral' });</script>
</body>
</html>`;

writeFileSync(OUT, html, "utf8");
console.log(`✓ Summary written to ${OUT}`);
